# Generated by Django 3.1.7 on 2021-07-31 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
