# Generated by Django 3.1.7 on 2021-08-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210801_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
