# Generated by Django 3.1.7 on 2021-08-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210802_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth',
            field=models.IntegerField(),
        ),
    ]
